--- #YAML:1.0
name: Cisco-ACL
version: 0.11
author:
  - James FitzGibbon, E<lt>jfitz@CPAN.orgE<gt>.
abstract: generate access control lists for Cisco IOS
license: perl
requires:
  Class::MethodMaker: 0
  Params::Validate: 0.65
recommends:
  CGI: 0
build_requires:
  Test::Exception: 0
  Test::More: 0
provides:
  Cisco::ACL:
    file: lib/Cisco/ACL.pm
    version: 0.12
generated_by: Module::Build version 0.25
